services:
  payload:
    build: .
    depends_on:
      - blogdb
    env_file:
      - .env
    networks:
      - payload_network
      - store_default
    restart: unless-stopped

  blogdb:
    image: postgres:17
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - payload_network
    restart: unless-stopped
      
volumes:
  pgdata:

networks:
  payload_network:
  store_default:
    external: true