version: '3'

services:
  payload:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - payload_network
      - store_default

  db:
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
        - data:/var/lib/postgresql/
    networks:
      - payload_network

volumes:
  data:

networks:
  payload_network:
  store_default:
    external: true