services:
  payload:
    build: .
    depends_on:
      - blogdb
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - payload_network
      - store_default

  blogdb:
    image: postgres:17
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
      - data:/var/lib/postgresql/
    networks:
      - payload_network
      
volumes:
  data:

networks:
  payload_network:
  store_default:
    external: true